[package]
name = "augorama"
version = "0.1.0"
authors = ["Ed Sweeney <ed@onextent.com>"]
edition = "2018"

[dependencies]
log = "0.4"
env_logger = "0.7"
warp = "0.1.20"
riker = "0.3.2"
either = "1.5"
