http://localhost:3030
-ks
Content-Type: application/json; charset=utf-8
--

--
GET /actor/person/Mary

--
GET /actor/person/Erdal

--
GET /actor/person/Erdal/pet/Sammy

--
GET /actor/person/Erdal/pet/Sammy/flee/Mikey

--
-v
GET /hiya/ahmed
