http://localhost:3030
-ks
Content-Type: application/json; charset=utf-8
--

--
POST /actor/person/Mary
[{"name": "my.name", "value": 1.3, "datetime": "2019-10-06T13:20:16Z"}]

--
GET /actor/person/Mary

--
GET /actor/person/Erdal/children

--
GET /actor/children
--
GET /actor/person/children
--
GET /actor/person/Erdal/children
--
GET /actor/person/Erdal/pet/children

--
POST /actor/person/Erdal/pet/Sammy
[{"name": "tag2.name", "value": 9.3, "datetime": "2019-10-06T13:20:16Z"}]

--
GET /actor/person/Erdal/pet/Sammy

--
-v
GET /actor/person/Erdal/pet/Sammy/flee/Mikey

--
GET /actor/pet/Sammy/owner/Erdal

--
-v
GET /hiya/ahmed
